algoritmo "temperaturacf"
// Descrição   : converter temperatura de celsius para fahrenheit
// Autor(a)    : Amanda Oliveira (@kmandzzz)
// Data atual  : 19/10/2020
var

celsius: inteiro
fahre: real

inicio

        escreva ("Digite a temperatura que queira converter: ")
        leia (celsius)
        fahre <- celsius * 9/5 + 32
      escreva ("temperatura em fahrenheit é igual a: " ,fahre)
fimalgoritmo

